import type { UITextTable } from '@/config/ui_texts/types';

const table: UITextTable = {
	ACCOUNT: 'Account',
	DELETE_ACCOUNT: 'Delete My Account',
	YOU_ARE_OFFLINE: 'You are currently offline, please connect to the internet.',
	ACCOUNT_NOT_FOUND: 'Account Not Found',
	BLOCK: 'Block',
	BLOCK_LIST: 'Block List',
	REPORT: 'Report',
	NOT_FOUND: 'Not Found',
	BLOCK_LIST_EMPTY: "You haven't blocked anyone",
	VERSION: 'Version',
	SUBMIT: 'Submit',
	ENTER_REPORT_REASON: 'Enter the reason for this report',
	LOCALE: 'EN',
	MAKE_FRIEND: 'Make friend?',
	YES: 'Yes',
	NO: 'No',
	HOW_TO_USE: 'How to use?',
	CHATROOM_TUTOR: `
		<li>Press the arrow at top-left corner to leave chat room</li>
		<li>Use the bottom area to text messages</li>
		<li>You can send reports by long-pressing any message bubbles</li>`,
	YOUR_APP_VERSION: 'Your Version',
	LATEST_APP_VERSION: 'Latest Version',
	NEED_UPDATE: 'Please update the app',
	LANGUAGE: 'Language',
	ERROR: 'Error',
	SETTINGS: 'Settings',
	CHAT_NOT_FOUND: 'Chat not found',
	TRIP_NOT_FOUND: 'Trip not found',
	FRIENDS: 'Friends',
	START_CHAT: 'Start Chatting',
	STRANGERS: 'Stranger',
	EQUIP: 'Equip',
	PROCESSING: 'Processing',
	TRIP_INFO: 'Trip Info',
	DATA: 'Data',
	LOADING: 'Loading',
	SAVE_MODIFIED: 'Save Modified',
	MUST_STAY_FOR_A_SEC: 'Your must stay for a while before leaving',
	READY_TO_GO: 'Off you go, wanna start a new trip',
	PEOPLE_NEARBY: 'People nearby',
	PROFILE: 'Profile',
	USER_NOT_FOUND: 'User not found',
	SYSTEM: 'System',
	EMAIL: 'E-mail',
	NAME: 'Name',
	SIGNIN: 'SignIn',
	SIGNOUT: 'SignOut',
	SIGNUP: 'SignUp',
	PASSWORD: 'Password',
	FORGOT_PWD: 'Forget password',
	CHANGE_PWD: 'Change password',
	NEW_PASSWORD: 'New password',
	CONFIRM_EXECUTION: 'Confirm',
	CONFIRM_PASSWORD: 'Confirm password',
	WELCOME: 'Welcome',
	WHERE_ARE_YOU_GOING: 'Where are you going?',
	UNKNOWN_ERROR: 'Unknown Error',
	INVALID_DATA_INPUT: 'Invalid Data Input',
	INVALID_EMAIL: 'Invalid Email',
	INVALID_EMAIL_OR_PASSWORD: 'Invalid Email or Password',
	INVALID_PASSWORD: 'Invalid Password',
	FAILED_TO_LOAD_DATA: 'Failed to load data',
	OPERATION_FAILED: 'Operation Failed',
	MUST_SIGNIN_FIRST: 'Must Sign In First',
	SIGNIN_FAILED: 'Sign in failed',
	WARNING: 'Warning',
	SUCCESS: 'Success'
	// ERROR_UNKNOWN: 'An unknown error has occurred',
	// ERROR_INVALID_EMAIL: 'Invalid email',
	// ERROR_INVALID_PASSWORD: 'Invalid password'
};

export { table as en };
