import type { UITextTable } from '@/config/ui_texts/types';

const table: UITextTable = {
	ACCOUNT: 'Account',
	ACCOUNT_NOT_FOUND: 'Account Not Found',
	VERSION: 'Version',
	LOCALE: 'English',
	LANGUAGE: 'Language',
	ERROR: 'Error',
	SETTINGS: 'Settings',
	FRIENDS: 'Friends',
	STRANGERS: 'Stranger',
	PEOPLE_NEARBY: 'People nearby',
	PROFILE: 'Profile',
	SYSTEM: 'System',
	EMAIL: 'E-mail',
	NAME: 'Name',
	SIGNIN: 'SignIn',
	SIGNOUT: 'SignOut',
	SIGNUP: 'SignUp',
	PASSWORD: 'Password',
	FORGOT_PWD: 'Forget password',
	CHANGE_PWD: 'Change password',
	NEW_PASSWORD: 'New password',
	CONFIRM_EXECUTION: 'Confirm',
	CONFIRM_PASSWORD: 'Confirm password',
	WELCOME: 'Welcome',
	WHERE_ARE_YOU_GOING: 'Where are you going?',
	UNKNOWN_ERROR: 'Unknown Error',
	INVALID_DATA_INPUT: 'Invalid Data Input',
	INVALID_EMAIL: 'Invalid Email',
	INVALID_EMAIL_OR_PASSWORD: 'Invalid Email or Password',
	INVALID_PASSWORD: 'Invalid Password',
	FAILED_TO_LOAD_DATA: 'Failed to load data',
	OPERATION_FAILED: 'Operation Failed',
	MUST_SIGNIN_FIRST: 'Must Sign In First',
	SIGNIN_FAILED: 'Sign in failed',
	WARNING: 'Warning',
	SUCCESS: 'Success'
	// ERROR_UNKNOWN: 'An unknown error has occurred',
	// ERROR_INVALID_EMAIL: 'Invalid email',
	// ERROR_INVALID_PASSWORD: 'Invalid password'
};

export { table as en };
