const TEXT_CODES = [
	'ACCOUNT',
	'ACCOUNT_NOT_FOUND',
	'CONFIRM_EXECUTION',
	'CONFIRM_PASSWORD',
	'CHANGE_PWD',
	'ERROR',
	'EMAIL',
	'FAILED_TO_LOAD_DATA',
	'FORGOT_PWD',
	'FRIENDS',
	'INVALID_DATA_INPUT',
	'INVALID_PASSWORD',
	'INVALID_EMAIL',
	'LOCALE',
	'LANGUAGE',
	'MUST_LOGIN_FIRST',
	'NAME',
	'NEW_PASSWORD',
	'OPERATION_FAILED',
	'PASSWORD',
	'PEOPLE_NEARBY',
	'PROFILE',
	'SETTINGS',
	'SIGNIN',
	'SIGNOUT',
	'SIGNUP',
	'STRANGERS',
	'SUCCESS',
	'SYSTEM',
	'UNKNOWN_ERROR',
	'VERSION',
	'WARNING',
	'WELCOME',
	'WHERE_ARE_YOU_GOING'
] as const;

type TextCode = (typeof TEXT_CODES)[number];
type UITextTable = Record<TextCode, string>;

export type { TextCode, UITextTable };
