import type { UITextTable } from '@/config/ui_texts/types';

const table: UITextTable = {
	ACCOUNT: '帳戶',
	ACCOUNT_NOT_FOUND: '找不到該帳戶',
	USER_NOT_FOUND: '找不到用戶',
	MUST_SIGNIN_FIRST: '請先登入',
	VERSION: '版本',
	TRIP_NOT_FOUND: '找不到行程',
	CHAT_NOT_FOUND: '找不到聊天室',
	LOCALE: '繁中',
	EQUIP: '裝備',
	SIGNIN_FAILED: '登入失敗',
	TRIP_INFO: '旅程資訊',
	DATA: '資料',
	SAVE_MODIFIED: '儲存變更',
	LOADING: '載入中',
	START_CHAT: '開始聊天',
	PROCESSING: '處理中',
	INVALID_EMAIL_OR_PASSWORD: '無效的Email或密碼',
	MUST_STAY_FOR_A_SEC: '請再待一下以開啟下一趟旅程',
	YOUR_APP_VERSION: '你的版本',
	LATEST_APP_VERSION: '最新版本',
	NEED_UPDATE: '請前往更新',
	READY_TO_GO: '準備就緒，要前往下個地點嗎？',
	LANGUAGE: '語言',
	ERROR: '錯誤',
	WARNING: '警告',
	SUCCESS: '成功',
	SETTINGS: '設定',
	FRIENDS: '好友',
	STRANGERS: '過客',
	PEOPLE_NEARBY: '附近的人',
	PROFILE: '個人資料',
	SYSTEM: '系統',
	EMAIL: 'E-mail',
	NAME: '名稱',
	SIGNIN: '登入',
	SIGNOUT: '登出',
	SIGNUP: '註冊',
	PASSWORD: '密碼',
	CONFIRM_EXECUTION: '確定執行',
	CONFIRM_PASSWORD: '確認密碼',
	OPERATION_FAILED: '操作失敗',
	INVALID_EMAIL: '無效的Email',
	INVALID_PASSWORD: '無效密碼',
	NEW_PASSWORD: '新密碼',
	FORGOT_PWD: '忘記密碼',
	CHANGE_PWD: '更改密碼',
	WELCOME: '歡迎來到 Verse U',
	WHERE_ARE_YOU_GOING: '去哪裡?',
	UNKNOWN_ERROR: '未知錯誤',
	INVALID_DATA_INPUT: '無效',
	FAILED_TO_LOAD_DATA: '無法載入資料'
} as const;

export { table as zh };
