const FILES = [
	{ name: '/android/', explain: 'Compiled code for native android app' },
	{
		name: '/assets/',
		explain: `<span>See <a href="" class="link link-hover">capacitor.js docs</a></span>`
	},
	{ name: '/ios/', explain: 'Compiled code for native iOS app' },
	{
		name: '/src/',
		explain: '',
		contents: [
			{ name: 'assets/', explain: 'Static assets generated by capacitor.js' },
			{
				name: 'lib/',
				explain: 'Alias as "@/"',
				contents: [
					{
						name: 'components/',
						explain: 'UI components',
						contents: [
							{
								name: 'audio_loader.svelte',
								explain:
									'Load native audio by <a href="https://github.com/capacitor-community/native-audio">this package</a>'
							},
							{ name: 'avatar.svelte', explain: 'Render by given profile' },
							{ name: 'dialog.svelte', explain: 'A dialog block container' },
							{ name: 'drawer.svelte', explain: 'A drawer block container' },
							{
								name: 'form.svelte',
								explain: 'A custom form element'
							},
							{ name: 'hold_btn.svelte', explain: '' },
							{ name: 'local_img.svelte', explain: '' },
							{ name: 'menu_toggler.svelte', explain: '' },
							{ name: 'submit_btn.svelte', explain: '' },
							{ name: 'subscriber.svelte', explain: '' },
							{ name: 'u_model.svelte', explain: '' }
						]
					},
					{
						name: 'config/',
						explain: 'Static, never change at run-time variables',
						contents: [{ name: 'ui_texts/', explain: 'Multilingual UI text tables' }]
					},
					{
						name: 'shadcn-components/',
						explain: 'Contains shadcn generated components, currently not in use but still keep it.'
					},
					{
						name: 'states/',
						explain: '',
						contents: [
							{ name: 'auth.svelte.ts', explain: 'Auth related states' },
							{ name: 'game.svelte.ts', explain: 'Game data related states' },
							{ name: 'sys.svelte.ts', explain: 'System info states' }
						]
					},
					{
						name: 'utils/',
						explain: 'Utilities',
						contents: [
							{
								name: 'subscribe/',
								explain: '',
								contents: [
									{ name: 'subscription.ts', explain: 'Define class Subscription' },
									{
										name: 'index.ts',
										explain: 'Module index & declare instances of Subscription'
									}
								]
							},
							{
								name: 'validate/',
								explain: 'Make sure data formats are fine',
								contents: [
									{ name: 'app_version.ts', explain: 'XX.XX.XX' },
									{ name: 'email.ts', explain: 'XX@XX.XX' },
									{ name: 'password.ts', explain: 'At least 8 chars' },
									{ name: 'uuid.ts', explain: '' },
									{ name: 'index.ts', explain: 'Module index' }
								]
							},
							{ name: 'error.ts', explain: 'Core error functions' },
							{ name: 'load.ts', explain: 'All in-game load functions' },
							{
								name: 'ml_texts.ts',
								explain: 'Define optimized functions to fetch ml_texts from DB'
							},
							{ name: 'preferences.ts', explain: 'Handling CapacitorJS preferences' },
							{ name: 'shadcn.ts', explain: 'Front-end code generated by shadcn-svelte' },
							{ name: 'storage.ts', explain: 'Handling file storage for native apps' },
							{ name: 'time.ts', explain: 'Time related operations' },
							{ name: 'updates.ts', explain: 'Determine if a client needs to update his/her app' }
						]
					},
					{ name: 'db.ts', explain: 'Define supabase client' }
				]
			},
			{
				name: 'routes/',
				explain: '',
				contents: [
					{
						name: 'auth/',
						explain: '',
						contents: [
							{ name: 'account/', explain: 'Account center' },
							{ name: 'create-profile/', explain: 'To create new profile' },
							{ name: 'reset-pwd/', explain: 'To reset password' },
							{
								name: 'utils/',
								explain: '',
								contents: [
									{ name: 'active.ts', explain: 'Check users activities' },
									{ name: 'password.ts', explain: 'Password related operations' },
									{ name: 'profile.ts', explain: 'Profile related operations' },
									{ name: 'signin.ts', explain: 'Sign in methods' },
									{ name: 'signout.ts', explain: 'Sign out methods' },
									{ name: 'signup.ts', explain: 'Sign up methods' },
									{ name: 'index.ts', explain: 'Module index' }
								]
							}
						]
					},
					{
						name: 'maintain/',
						explain: 'When the app is under maintenance, redirect to this page'
					},
					{
						name: 'map/',
						explain: 'The /map page',
						contents: [
							{ name: 'utils/', explain: '', contents: [{ name: 'index.ts', explain: '' }] },
							{ name: '+page.svelte', explain: '' }
						]
					},
					{
						name: 'me/',
						explain: 'The /me page',
						contents: [
							{
								name: 'utils/',
								explain: '',
								contents: [
									{ name: 'selfie.ts', explain: '' },
									{ name: 'wearing.ts', explain: '' },
									{ name: 'index.ts', explain: '' }
								]
							}
						]
					},
					{
						name: 'side_menu/',
						explain: '',
						contents: [
							{
								name: 'mini_game',
								explain: '',
								contents: [
									{ name: 'config.ts', explain: '' },
									{ name: 'index.ts', explain: '' },
									{ name: 'hai_an.svelte', explain: '' },
									{ name: 'mini_game.svelte', explain: '' }
								]
							},
							{
								name: 'others/',
								explain: '',
								contents: [
									{ name: 'config.ts', explain: '' },
									{ name: 'blocks.svelte', explain: '' },
									{ name: 'coupons.svelte', explain: '' },
									{ name: 'others.svelte', explain: '' },
									{ name: 'index.ts', explain: '' }
								]
							},
							{ name: 'config.ts', explain: '' },
							{ name: 'settings.svelte', explain: '' },
							{ name: 'side_menu.svelte', explain: '' },
							{ name: 'trip_info.svelte', explain: '' },
							{ name: 'index.ts', explain: '' }
						]
					},
					{
						name: 'social/',
						explain: 'The /social page',
						contents: [
							{
								name: 'utils/',
								explain: '',
								contents: [
									{ name: 'chat_info.ts', explain: '' },
									{ name: 'message.ts', explain: '' },
									{ name: 'reports.ts', explain: '' },
									{ name: 'index.ts', explain: '' }
								]
							},
							{ name: 'input.svelte', explain: '' },
							{ name: 'chat_list.svelte', explain: '' },
							{ name: 'message.svelte', explain: '' },
							{ name: 'room.svelte', explain: '' },
							{ name: 'story.svelte', explain: '' },
							{ name: '+page.svelte', explain: '' }
						]
					},
					{
						name: 'update/',
						explain:
							"When the app's version is too old and needs to update, redirect to this page. The method to determine if update is needed are <a href='#/src/lib/utils/updates.ts' >here</a>"
					},
					{ name: 'menu.svelte', explain: 'The main bottom menu' },
					{ name: 'my_profile.svelte', explain: 'To render users profile at top-left corner' },
					{
						name: 'system_message.svelte',
						explain: 'To render system message while doing async operations'
					},
					{ name: 'trip_status.svelte', explain: 'Not used anymore' },
					{ name: 'index.ts', explain: 'Module index' }
				]
			}
		]
	},
	{
		name: '/static/',
		explain: '',
		contents: [
			{ name: 'audios/', explain: '' },
			{ name: 'fonts/', explain: '' },
			{ name: 'icons/', explain: '' },
			{ name: 'images/', explain: '' },
			{ name: 'models/', explain: '' },
			{ name: 'videos/', explain: '' },
			{ name: 'favicon.png', explain: '' },
			{ name: 'manifest.json', explain: '' }
		]
	}
];

export { FILES };
