import type { UITextTable } from '@/config/ui_texts/types';

const table: UITextTable = {
	ACCOUNT: '帳戶',
	PLAYER_INFO: '玩家資訊',
	YOU_ARE_OFFLINE: '您目前處於離線狀態，請連上網路以使用本 App',
	ACCOUNT_NOT_FOUND: '找不到該帳戶',
	HAI_AN_SUCCESS: '互動成功，在LED螢幕裡尋找自己的化身吧！',
	NOTHING: '無',
	RELATIONSHIP: '關係',
	SOUND_VOLUME: '音效音量',
	MUSIC_VOLUME: '音樂音量',
	HAI_AN_HINT:
		'臺南海安路上，有兩座LED螢幕，那裡展示著Verse U的世界。輸入螢幕上的通關密碼，讓自己的角色出現在裡面吧！',
	HAI_AN_ROAD: '海安路',
	DELETE_ACCOUNT: '刪除我的帳號',
	REFRESH: '重新整理',
	YOU_JUST_TOOK_SELFIE: '要上傳這張自拍照嗎？',
	HOW_TO_USE: '如何使用',
	MAKE_FRIEND: '交個朋友？',
	CHATROOM_TUTOR: `
		<li>按左上角返回鍵已離開本頁</li>
		<li>底下的區域可用來傳送訊息</li>
		<li>長按任何訊息，可以檢舉該訊息</li>`,
	YES: '是',
	NO: '否',
	USER_NOT_FOUND: '找不到用戶',
	MUST_SIGNIN_FIRST: '請先登入',
	COUPON_USED: '已兌換',
	CANCEL: '取消',
	REDEEM: '兌換',
	SIDE_MENU_BLOCKS_TITLE: '封鎖名單',
	SIDE_MENU_OTHERS_TITLE: '其他',
	SIDE_MENU_TUTORIAL_TITLE: '教學',
	PASSWORD_LIMIT: '密碼必須至少八個字元',
	CONGRATULATION: '恭喜',
	SIDE_MENU_COUPONS_TITLE: '優惠券',
	YOU_CAN_HAVE_COUPON: '您已符合優惠券領取資格',
	COUPON_INFO: '優惠內容',
	HOW_TO_VIEW_COUPON: '領取完畢後，可至右側選單[其他]->[優惠券]查看所擁有之優惠券。',
	SIDE_MENU_SETTINGS_TITLE: '設定',
	SIDE_MENU_MINI_GAME_TITLE: '小遊戲',
	SIDE_MENU_TRIP_INFO_TITLE: '旅程資訊',
	SIDE_MENU_HAI_AN_TITLE: '海安路互動',
	NOT_FOUND: '找不到',
	VERSION: '版本',
	BLOCK_LIST_EMPTY: '您尚未封鎖任何人',
	SUBMIT: '提交',
	ENTER_REPORT_REASON: '請輸入檢舉原因',
	TRIP_NOT_FOUND: '找不到行程',
	BLOCK_LIST: '封鎖名單',
	CHAT_NOT_FOUND: '找不到聊天室',
	LOCALE: '繁中',
	EQUIP: '裝備',
	SIGNIN_FAILED: '登入失敗',
	TRIP_INFO: '旅程資訊',
	DATA: '資料',
	SAVE_MODIFIED: '儲存變更',
	BLOCK: '封鎖',
	REPORT: '檢舉',
	LOADING: '載入中',
	START_CHAT: '開始聊天',
	PROCESSING: '處理中',
	INVALID_EMAIL_OR_PASSWORD: '無效的Email或密碼',
	MUST_STAY_FOR_A_SEC: '請再待一下以開啟下一趟旅程',
	YOUR_APP_VERSION: '你的版本',
	LATEST_APP_VERSION: '最新版本',
	NEED_UPDATE: '請前往更新',
	READY_TO_GO: '準備就緒，要前往下個地點嗎？',
	LANGUAGE: '語言',
	ERROR: '錯誤',
	WARNING: '警告',
	SUCCESS: '成功',
	SETTINGS: '設定',
	GET_COUPON: '領取優惠券',
	GET: '領取',
	FRIENDS: '好友',
	STRANGERS: '過客',
	COUPON_LIMIT: '限量',
	COUPON_UNIT: '份',
	REDEEM_CONFIRM: '注意！請經櫃檯人員確認過後，再按下確認兌換鍵。否則票券將顯示為已兌換，導致無法享有優惠。',
	PEOPLE_NEARBY: '附近的玩家',
	PROFILE: '個人資料',
	SYSTEM: '系統',
	EMAIL: 'E-mail',
	NAME: '名稱',
	SIGNIN: '登入',
	SIGNOUT: '登出',
	SIGNUP: '註冊',
	PASSWORD: '密碼',
	CONFIRM_EXECUTION: '確定執行',
	CONFIRM_PASSWORD: '確認密碼',
	OPERATION_FAILED: '操作失敗',
	INVALID_EMAIL: '無效的Email',
	INVALID_PASSWORD: '無效密碼',
	NEW_PASSWORD: '新密碼',
	FORGOT_PWD: '忘記密碼',
	CHANGE_PWD: '更改密碼',
	WELCOME: '歡迎來到 Verse U',
	WHERE_ARE_YOU_GOING: '去哪裡?',
	UNKNOWN_ERROR: '未知錯誤',
	INVALID_DATA_INPUT: '無效',
	FAILED_TO_LOAD_DATA: '無法載入資料',
	ANONYMOUS_LOGIN: '匿名登入',
	SELECT_LOCALE: '選擇語言',
	CAPTCHA: '驗證',
	TELEPORT: '傳送',
	ONE_O_ONE: '101',
	ONE_O_ONE_TELEPORT_HINT: '在台灣最高的建築物 -- 101，有四個 LED 看板，展示著Verse U的世界。輸入看板上的通關密碼，讓自己的角色出現在裡面吧！',
	ONE_O_ONE_REGISTER_HINT: '在這裡輸入 email, 密碼並註冊，可以獲得 500 Unergy，註冊後會開啟下載遊戲頁面。',
	INTRODUCTION: '介紹',
} as const;

export { table as zh };
